name: CI Workflow  # Give your workflow a name

on:
  push:
    branches:
      - main  # Runs when changes are pushed to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Specifies the runner (Ubuntu) to execute the job on

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Checks out your code from the repository

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Sets up a Node.js environment with version 16

      - name: Install dependencies
        run: npm install  # Installs project dependencies

      - name: Run tests
        run: npm test  # Runs tests (if any) in your project
