name: Trigger on Push to Specific Branch

on:
  push:
    branches:
      - <main>  # Replace <branch-name> with the name of your branch

jobs:
  run-on-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run a script or command
        run: echo "A push event triggered this workflow on branch <main>."
